name: Build and Test
on: [push, pull_request]

env:
  GO_VERSION: 1.22.11

jobs:
  env-setup:
    name: Environment Setup
    runs-on: ubuntu-latest
    outputs:
      go_bin: ${{ steps.set_env.outputs.go_bin }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out source
        uses: actions/checkout@v3

      - name: Set environment variables
        id: set_env
        run: |
          echo "GOBIN=$HOME/go/bin" >> $GITHUB_ENV
          echo "GOCACHE=$RUNNER_TEMP/go-build" >> $GITHUB_ENV
          echo "GO_BIN=$HOME/go/bin" >> $GITHUB_ENV
          echo "go_bin=$HOME/go/bin" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: env-setup
    steps:
      - name: Build
        run: make build

  test-cover:
    name: Unit coverage
    runs-on: ubuntu-latest
    needs: env-setup
    steps:
      - name: Install dependencies
        run: make goimports lint install

      - name: Verify installed binaries
        run: ls -l ${{ needs.env-setup.outputs.go_bin }}

      - name: Run coverage tests
        run: make unit-cover

      - name: Send top-level coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt
          flag-name: btcd
          parallel: true

      - name: Send btcec coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: btcec/coverage.txt
          flag-name: btcec
          parallel: true

      - name: Send btcutil coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: btcutil/coverage.txt
          flag-name: btcutil
          parallel: true

      - name: Send btcutil coverage for psbt package
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: btcutil/psbt/coverage.txt
          flag-name: btcutilpsbt
          parallel: true

      - name: Notify coveralls all reports sent
        uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true

  test-race:
    name: Unit race
    runs-on: ubuntu-latest
    needs: env-setup
    steps:
      - name: Run race tests
        run: make unit-race
